---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore, bck]
permalink: /:title ## disables post output
timezone: null
lsi: false
favicon: "img/favico.ico"
touch_icon: "img/apple-touch-icon.png"
markdown: kramdown 
#highlighter: rouge 



### content configuration ###
title:       "IPDRM23: Sixth International Workshop on Emerging Parallel and Distributed Runtime Systems and Middleware"
keywords:    "hpc, user, Runtimes, Middleware, ipdrm20, ipdrm, supercomputing"
description: "Sixth workshop on Parallel and distributed runtiems and middleware"
source_link: "https://github.com/ipdrm/ipdrm.github.io"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-55665759-3


### template colors, used site-wide via css ###
colors:
  green:     '#377f1c'
  black:     '#111111'
  white:     '#ffffff'
  blue:      '#779ecb'
  orange:    '#cba477'
  turquoise: '#77c8cb'

# Original Bright colors
  # black:     '#111111'
  # white:     '#f8f8f8'
  # blue:      '#49a7e9'
  # green:     '#9bcf2f'
  # purple:    '#c869bf'
  # orange:    '#fab125'
  # turquoise: '#0fbfcf'

kramdown:
   auto_ids: false
